// <auto-generated />
namespace TP_PWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEstadoAndData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEstadoAndData));
        
        string IMigrationMetadata.Id
        {
            get { return "202101082346380_addEstadoAndData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
